language: python
sudo: false  # Be explicit.

before_install:
  - pip install -r pip-requirements.txt

install:
  - pip install coveralls

# command to run tests
script:
 - nosetests --config=nose.cfg
##  - nosetests --with-coverage --cover-package=elementary

after_success:
  - codeclimate-test-reporter
  - codecov
  - coveralls
